# Generated by Django 3.2.6 on 2021-09-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_home',
            field=models.SmallIntegerField(default=1),
        ),
    ]
